### PR TITLE
Add button text updated from "Add to notes" to "Add" only.

### PR DESCRIPTION
**Pull request by 0day-anon**

### CODE REVIEW

**Comment by imsamuel** [comment]
Thanks!

**Comment by 0day-anon** [comment]
@imsamuel  in my hacktoberfest profile after submitting the PR it is showing ineligible Repo for hacktoberfest, can you please check on that.

**Comment by 0day-anon** [comment]
Can you add "Hacktoberfest" and "good first issue" labels to this request so that this will qualify for hacktoberfest.

**Comment by imsamuel** [comment]
> Can you add "Hacktoberfest" and "good first issue" labels to this request so that this will qualify for hacktoberfest.

Have added a "hacktoberfest" label to this repository, see the new [update](https://hacktoberfest.digitalocean.com/hacktoberfest-update). Have added a "hacktoberfest-accepted" label to this pull request as well which should be redundant as the pull request has been merged.

**Comment by 0day-anon** [comment]
@imsamuel  Thank you!

**Comment by imsamuel** [comment]
No worries! :)

**Pull request merged**
